In [5]:
import glassdoor_scraper as gs
import pandas as pd

In [6]:
path = "/home/nicolas/bin/chromedriver"

df = gs.get_jobs("data scientist", 30, False, path, 9)

Progress: 0/50
Progress: 1/50
Progress: 2/50
Progress: 3/50
Progress: 4/50
Progress: 5/50
Progress: 6/50
Progress: 7/50
Progress: 8/50
Progress: 9/50
Progress: 10/50
Progress: 11/50
Progress: 12/50
Progress: 13/50
Progress: 14/50
Progress: 15/50
Progress: 16/50
Progress: 17/50
Progress: 18/50
Progress: 19/50
Progress: 20/50
Progress: 21/50
Progress: 22/50
Progress: 23/50
Progress: 24/50
Progress: 25/50
Progress: 26/50
Progress: 27/50
Progress: 28/50
Progress: 29/50
Scraping terminated before reaching target number of jobs. Needed 50, got 30.

In [7]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,Data Scientist co op (Spring/Summer 2023),$29.00 Per Hour(Employer est.),4.2,Johnson & Johnson,"Raritan, NJ",-1,-1,-1,-1,-1,-1,-1,-1
1,Jr. Data Scientist,$78K - $116K (Glassdoor est.),2.9,UMortgage,Remote,-1,-1,-1,-1,-1,-1,-1,-1
2,Data Scientist (Level I - II),$73K - $113K (Glassdoor est.),3.6,"BEN Group, Inc","Provo, UT",-1,-1,-1,-1,-1,-1,-1,-1
3,Data Scientist,$80K - $121K (Glassdoor est.),3.7,Big Fish Games,"Las Vegas, NV",-1,-1,-1,-1,-1,-1,-1,-1
4,Data Scientist - All Levels,$59K - $100K (Glassdoor est.),4.5,Interclypse Inc,"Reston, VA",-1,-1,-1,-1,-1,-1,-1,-1
5,Data Scientist,$81K - $117K (Glassdoor est.),3.6,PNC Financial Services Group,"Cleveland, OH",-1,-1,-1,-1,-1,-1,-1,-1
6,Customer Product Data Scientist,-1,3.4,Treehouse Foods,Remote,-1,-1,-1,-1,-1,-1,-1,-1
7,Junior Data Scientist,$80K - $117K (Glassdoor est.),4.2,Logistics Management Institute,"Camp Lejeune, NC",-1,-1,-1,-1,-1,-1,-1,-1
8,Data Scientist,$95K - $150K (Employer est.),5.0,Grey Matters Defense Solutions,"Englewood, CO",-1,-1,-1,-1,-1,-1,-1,-1
9,Data Scientist,-1,4.2,University of Florida,Florida,-1,-1,-1,-1,-1,-1,-1,-1
10,"Data Scientist, University Graduate (Data Anal...",$85K - $134K (Glassdoor est.),3.6,TikTok,"Los Angeles, CA",-1,-1,-1,-1,-1,-1,-1,-1
11,Data Scientist Co-Op (Spring 2023),$65K - $108K (Glassdoor est.),3.9,HERSHEY MX,"Hershey, PA",-1,-1,-1,-1,-1,-1,-1,-1
12,Data Visualization Scientist,$59K - $80K (Glassdoor est.),3.6,Optimal Inc.,"Dearborn, MI",-1,-1,-1,-1,-1,-1,-1,-1
13,Machine Learning Data Scientist,$82K - $117K (Glassdoor est.),4.2,HP,"Corvallis, OR",-1,-1,-1,-1,-1,-1,-1,-1
14,Data Scientist,$140K - $175K (Employer est.),-1,Spade,"New York, NY",-1,-1,-1,-1,-1,-1,-1,-1
15,Forensic Scientist Data Review I (NDOT),$44K - $70K (Glassdoor est.),3.8,Abbott Laboratories,"Gretna, LA",-1,-1,-1,-1,-1,-1,-1,-1
16,Decision Scientist,$86K - $119K (Glassdoor est.),4.9,KUNGFU.AI,"Austin, TX",-1,-1,-1,-1,-1,-1,-1,-1
17,Data Scientist,$81K - $130K (Glassdoor est.),5.0,Markesman Group,"Fort Meade, MD",-1,-1,-1,-1,-1,-1,-1,-1
18,Jr. Data Scientist,$69K - $108K (Glassdoor est.),-1,Tek Ninjas,"Dallas, TX",-1,-1,-1,-1,-1,-1,-1,-1
19,Data Scientist (Contract),$76K - $108K (Glassdoor est.),4.8,Audere,"Seattle, WA",-1,-1,-1,-1,-1,-1,-1,-1
20,Data Labeler - Contract,$20.00 - $25.00 Per Hour(Employer est.),4.8,EvolutionIQ,"New York, NY",-1,-1,-1,-1,-1,-1,-1,-1
21,Data Strategist,$72K - $103K (Glassdoor est.),4.2,Booz Allen Hamilton,"Bethesda, MD",-1,-1,-1,-1,-1,-1,-1,-1
22,Data Scientist,$87K - $141K (Glassdoor est.),3.9,WTW,"White Plains, NY",-1,-1,-1,-1,-1,-1,-1,-1
23,Data Scientist,$79K - $122K (Glassdoor est.),-1,Tek Ninjas,"Cincinnati, OH",-1,-1,-1,-1,-1,-1,-1,-1
24,Data Scientist,$60.00 - $75.00 Per Hour(Employer est.),3.5,Largeton Inc,Remote,-1,-1,-1,-1,-1,-1,-1,-1
25,Data Scientist,-1,-1,SWI,"Bellevue, WA",-1,-1,-1,-1,-1,-1,-1,-1
26,Data Scientist- 295013,$89K - $126K (Glassdoor est.),4.1,Grainger,"Lake Forest, IL",-1,-1,-1,-1,-1,-1,-1,-1
27,Biomedical Data Scientist,$74K - $121K (Glassdoor est.),3.2,Retia Medical,"White Plains, NY",-1,-1,-1,-1,-1,-1,-1,-1
28,Associate Data Scientist,-1,3.1,Dyson,"Chicago, IL",-1,-1,-1,-1,-1,-1,-1,-1
29,Data Scientist Apprentice,$61K - $97K (Glassdoor est.),3.9,Toyota,"Plano, TX",-1,-1,-1,-1,-1,-1,-1,-1

In [9]:
df.to_csv('glassdoor_jobs.csv', index = False)