In [1]:
import glassdoor_scraper as gs
import pandas as pd

In [3]:
path = "/home/nicolas/bin/chromedriver"

df = gs.get_jobs("data scientist", 15, False, path, 9)

Progress: 0/15
Progress: 1/15
Progress: 2/15
Progress: 3/15
Progress: 4/15
Progress: 5/15
Progress: 6/15
Progress: 7/15
Progress: 8/15
Progress: 9/15
Progress: 10/15
Progress: 11/15
Progress: 12/15
Progress: 13/15
Progress: 14/15
Progress: 15/15
Scraping terminated before reaching target number of jobs. Needed 15, got 15.

In [4]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,Data Scientist co op (Spring/Summer 2023),$29.00 Per Hour(Employer est.),4.2,Johnson & Johnson,"Raritan, NJ",-1,-1,-1,-1,-1,-1,-1,-1
1,Data Scientist,$81K - $117K (Glassdoor est.),3.6,PNC Financial Services Group,"Cleveland, OH",-1,-1,-1,-1,-1,-1,-1,-1
2,Data Scientist (Level I - II),$73K - $113K (Glassdoor est.),3.6,"BEN Group, Inc","Provo, UT",-1,-1,-1,-1,-1,-1,-1,-1
3,Data Scientist - All Levels,$59K - $100K (Glassdoor est.),4.5,Interclypse Inc,"Reston, VA",-1,-1,-1,-1,-1,-1,-1,-1
4,Customer Product Data Scientist,-1,3.4,Treehouse Foods,Remote,-1,-1,-1,-1,-1,-1,-1,-1
5,Data Scientist,$80K - $121K (Glassdoor est.),3.7,Big Fish Games,"Las Vegas, NV",-1,-1,-1,-1,-1,-1,-1,-1
6,Data Visualization Scientist,$59K - $80K (Glassdoor est.),3.6,Optimal Inc.,"Dearborn, MI",-1,-1,-1,-1,-1,-1,-1,-1
7,Junior Data Scientist,$80K - $117K (Glassdoor est.),4.2,Logistics Management Institute,"Camp Lejeune, NC",-1,-1,-1,-1,-1,-1,-1,-1
8,Data Scientist,$140K - $175K (Employer est.),-1,Spade,"New York, NY",-1,-1,-1,-1,-1,-1,-1,-1
9,Data Scientist,$81K - $130K (Glassdoor est.),5.0,Markesman Group,"Fort Meade, MD",-1,-1,-1,-1,-1,-1,-1,-1
10,Machine Learning Data Scientist,$82K - $117K (Glassdoor est.),4.2,HP,"Corvallis, OR",-1,-1,-1,-1,-1,-1,-1,-1
11,Data Strategist,$72K - $103K (Glassdoor est.),4.2,Booz Allen Hamilton,"Bethesda, MD",-1,-1,-1,-1,-1,-1,-1,-1
12,"Data Scientist, University Graduate (Data Anal...",$85K - $134K (Glassdoor est.),3.6,TikTok,"Los Angeles, CA",-1,-1,-1,-1,-1,-1,-1,-1
13,Data Scientist,-1,-1,SWI,"Bellevue, WA",-1,-1,-1,-1,-1,-1,-1,-1
14,Data Scientist - NLP,-1,3.8,Bose,Remote,-1,-1,-1,-1,-1,-1,-1,-1